### PR TITLE
Update Changelog (cause you didn't lol) and add draft workflow

### PR DESCRIPTION
**Pull request by auggeeo**
update ur changelogs tech grrrrrrrrrrrrrrrrrr

### CODE REVIEW

**Comment by TechStudent10** [comment]
what's the other workflow for?

**Comment by auggeeo** [comment]
making draft releases and get the latest stuff in the changelog.md and puts it as the description and puts the .geode file from your latest successful build into the release

**Comment by TechStudent10** [comment]
> making draft releases and get the latest stuff in the changelog.md and puts it as the description and puts the .geode file from your latest successful build into the release

oh cool

**Comment by auggeeo** [comment]
yeppi!

**Pull request merged**
