### PR TITLE
Rename CustomPresence and add applicationId to readme

### PR DESCRIPTION
**Pull request by auggeeo**
Rename CustomPresence and add applicationId to readme

### CODE REVIEW

**Comment by coopeeo** [comment]
imma add the cpp stuff

**Comment by coopeeo** [comment]
nvm

**Comment by TechStudent10** [comment]
Uh kinda a useless change imo. The rename is gonna break things and I'm not even going in the applicationId route. Even if I did, it should be in `initDiscordRP` not update.

**Comment by auggeeo** [comment]
omg i'm so stupid i was gonna change it but while changing the cpp files but i totally forgot that i had readme changes lol

**Pull request closed without merging**
